<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| File and Directory Modes
|--------------------------------------------------------------------------
|
| These prefs are used when checking and setting modes when working
| with the file system.  The defaults are fine on servers with proper
| security, but you may wish (or even need) to change the values in
| certain environments (Apache running a separate process for each
| user, PHP under CGI with Apache suEXEC, etc.).  Octal values should
| always be used to set the mode correctly.
|
*/
define('FILE_READ_MODE', 0644);
define('FILE_WRITE_MODE', 0666);
define('DIR_READ_MODE', 0755);
define('DIR_WRITE_MODE', 0777);

/*
|--------------------------------------------------------------------------
| File Stream Modes
|--------------------------------------------------------------------------
|
| These modes are used when working with fopen()/popen()
|
*/

define('FOPEN_READ',							'rb');
define('FOPEN_READ_WRITE',						'r+b');
define('FOPEN_WRITE_CREATE_DESTRUCTIVE',		'wb'); // truncates existing file data, use with care
define('FOPEN_READ_WRITE_CREATE_DESTRUCTIVE',	'w+b'); // truncates existing file data, use with care
define('FOPEN_WRITE_CREATE',					'ab');
define('FOPEN_READ_WRITE_CREATE',				'a+b');
define('FOPEN_WRITE_CREATE_STRICT',				'xb');
define('FOPEN_READ_WRITE_CREATE_STRICT',		'x+b');


//M02USERS_SIM
const TBL_M02USERS_DS = "M02USERS_SIM";
const M02LOGINNAME = "M02USERS_SIM.LOGINNAME";
const M02PASSWOD = "M02USERS_SIM.PASSWOD";
const M02NAMA = "M02USERS_SIM.NAMA";
const M02EMAIL = "M02USERS_SIM.EMAIL";
const M02NIP = "M02USERS_SIM.NIP";
const M02USER_GROUP = "M02USERS_SIM.USER_GROUP";
const M02KD_KEC = "M02USERS_SIM.KD_KECAMATAN";
const M02KD_KEL = "M02USERS_SIM.KD_KELURAHAN";
const M02OLDPASSWOD = "M02USERS_SIM.OLD_PASSWOD";

//meh?
const M02UPT = "M02USERS_SIM.KD_UPT";
const RKD_UPT = "REF_UPT.KD_UPT";
const TBL_REF_UPT = "REF_UPT";

//M03USRGROUP_SIM
const TBL_M03USRGROUP_DS = "M03USRGROUP_SIM";
const M03USER_GROUP = "M03USRGROUP_SIM.USER_GROUP";
const M03KETERANGAN = "M03USRGROUP_SIM.KETERANGAN";

//REF_KECAMATAN
const TBL_REF_KECAMATAN = "REF_KECAMATAN";
const KD_PROPINSI_KEC = "REF_KECAMATAN.KD_PROPINSI";
const KD_DATI2_KEC = "REF_KECAMATAN.KD_DATI2";
const KD_KECAMATAN_KEC = "REF_KECAMATAN.KD_KECAMATAN";
const NM_KECAMATAN = "REF_KECAMATAN.NM_KECAMATAN";

//REF_KELURAHAN
const TBL_REF_KELURAHAN = "REF_KELURAHAN";
const KD_PROPINSI_KEL = "REF_KELURAHAN.KD_PROPINSI";
const KD_DATI2_KEL = "REF_KELURAHAN.KD_DATI2";
const KD_KECAMATAN_KEL = "REF_KELURAHAN.KD_KECAMATAN";
const KD_KELURAHAN = "REF_KELURAHAN.KD_KELURAHAN";
const KD_SEKTOR = "REF_KELURAHAN.KD_SEKTOR";
const NM_KELURAHAN = "REF_KELURAHAN.NM_KELURAHAN";
const NO_KELURAHAN = "REF_KELURAHAN.NO_KELURAHAN";
const KD_POS_KELURAHAN = "REF_KELURAHAN.KD_POS_KELURAHAN";


//eh
//SPPT
CONST TBL_SPPT = "SPPT";
CONST SPPT__KD_PROPINSI = "KD_PROPINSI";
CONST SPPT__KD_DATI2 = "KD_DATI2";
CONST SPPT__KD_KECAMATAN = "KD_KECAMATAN";
CONST SPPT__KD_KELURAHAN = "KD_KELURAHAN";
CONST SPPT__KD_BLOK = "KD_BLOK";
CONST NO_URUT = "NO_URUT";
CONST KD_JNS_OP = "KD_JNS_OP";
CONST THN_PAJAK_SPPT = "THN_PAJAK_SPPT";
CONST SIKLUS_SPPT = "SIKLUS_SPPT";
CONST KD_KANWIL = "KD_KANWIL";
CONST KD_KANTOR = "KD_KANTOR";
CONST KD_TP = "KD_TP";
CONST NM_WP_SPPT = "NM_WP_SPPT";
CONST JLN_WP_SPPT = "JLN_WP_SPPT";
CONST BLOK_KAV_NO_WP_SPPT = "BLOK_KAV_NO_WP_SPPT";
CONST RW_WP_SPPT = "RW_WP_SPPT";
CONST RT_WP_SPPT = "RT_WP_SPPT";
CONST KELURAHAN_WP_SPPT = "KELURAHAN_WP_SPPT";
CONST KOTA_WP_SPPT = "KOTA_WP_SPPT";
CONST KD_POS_WP_SPPT = "KD_POS_WP_SPPT";
CONST NPWP_SPPT = "NPWP_SPPT";
CONST NO_PERSIL_SPPT = "NO_PERSIL_SPPT";
CONST KD_KLS_TANAH = "KD_KLS_TANAH";
CONST THN_AWAL_KLS_TANAH = "THN_AWAL_KLS_TANAH";
CONST KD_KLS_BNG = "KD_KLS_BNG";
CONST THN_AWAL_KLS_BNG = "THN_AWAL_KLS_BNG";
CONST TGL_JATUH_TEMPO_SPPT = "TGL_JATUH_TEMPO_SPPT";
CONST LUAS_BUMI_SPPT = "LUAS_BUMI_SPPT";
CONST LUAS_BNG_SPPT = "LUAS_BNG_SPPT";
CONST NJOP_BUMI_SPPT = "NJOP_BUMI_SPPT";
CONST NJOP_BNG_SPPT = "NJOP_BNG_SPPT";
CONST NJOP_SPPT = "NJOP_SPPT";
CONST NJOPTKP_SPPT = "NJOPTKP_SPPT";
CONST PBB_TERHUTANG_SPPT = "PBB_TERHUTANG_SPPT";
CONST FAKTOR_PENGURANG_SPPT = "FAKTOR_PENGURANG_SPPT";
CONST PBB_YG_HARUS_DIBAYAR_SPPT = "PBB_YG_HARUS_DIBAYAR_SPPT";
CONST STATUS_PEMBAYARAN_SPPT = "STATUS_PEMBAYARAN_SPPT";
CONST STATUS_TAGIHAN_SPPT = "STATUS_TAGIHAN_SPPT";
CONST STATUS_CETAK_SPPT = "STATUS_CETAK_SPPT";
CONST TGL_TERBIT_SPPT = "TGL_TERBIT_SPPT";
CONST TGL_CETAK_SPPT = "TGL_CETAK_SPPT";
CONST NIP_PENCETAK_SPPT = "NIP_PENCETAK_SPPT";

//TTSPPT123_PREAPPROVE

CONST TBL_TTSPPT123_PREAPPROVE = "TTSPPT123_PREAPPROVE";
CONST LOGINNAME = "LOGINNAME";
CONST KD_PROPINSI_PRE = "KD_PROPINSI";
CONST KD_DATI2_PRE = "KD_DATI2";
CONST KD_KECAMATAN_PRE = "KD_KECAMATAN";
CONST KD_KELURAHAN_PRE = "KD_KELURAHAN";
CONST THN_PAJAK_SPPT_PRE = "THN_PAJAK_SPPT";
CONST JUMLAH = "JUMLAH";
CONST BUKU = "BUKU";
CONST APPROVED = "APPROVED";
CONST NM_KELURAHAN_PRE = "NM_KELURAHAN";

//TTSPPT45_PREAPPROVE
CONST TBL_TTSPPT45_PREAPPROVE = "TTSPPT45_PREAPPROVE";
CONST THN_PAJAK_SPPT_45PRE = "THN_PAJAK_SPPT";
CONST KD_JNS_OP_45PRE = "KD_JNS_OP";
CONST NO_URUT_45PRE = "NO_URUT";
CONST KD_BLOK_45PRE = "KD_BLOK";
CONST KD_KELURAHAN_45PRE = "KD_KELURAHAN";
CONST KD_KECAMATAN_45PRE = "KD_KECAMATAN";
CONST KD_DATI2_45PRE = "KD_DATI2";
CONST KD_PROPINSI_45PRE = "KD_PROPINSI";
CONST PBB_YG_HARUS_DIBAYAR_SPPT_45PRE = "PBB_YG_HARUS_DIBAYAR_SPPT";
CONST NM_WP_SPPT_45PRE = "NM_WP_SPPT";
CONST NM_KECAMATAN_45PRE = "NM_KECAMATAN";
CONST NM_KELURAHAN_45PRE = "NM_KELURAHAN";
CONST LOGINNAME_45PRE = "LOGINNAME";
CONST BUKU_45PRE = "BUKU";
CONST APPROVED_45PRE = "APPROVED";

//TTSPPT12H
CONST TBL_TTSPPT123H = "TTSPPT12H";
CONST KD_PROPINSI_123H = "KD_PROPINSI";
CONST KD_DATI2_123H = "KD_DATI2";
CONST KD_KECAMATAN_123H = "KD_KECAMATAN";
CONST KD_KELURAHAN_123H = "KD_KELURAHAN";
CONST THN_PAJAK_SPPT_123H = "THN_PAJAK_SPPT";
CONST NAMA_PENERIMA_SPPT = "NAMA_PENERIMA_SPPT";
CONST NIK_PENERIMA_SPPT = "NIK_PENERIMA_SPPT";
CONST KETERANGAN = "KETERANGAN";
CONST TGL_TERIMA_SPPT = "TGL_TERIMA_SPPT";
CONST TGL_JATUH_TEMPO_SPPT6BL = "TGL_JATUH_TEMPO_SPPT6BL";
CONST STATUS_TERIMA_SPPT = "STATUS_TERIMA_SPPT";
CONST TGL_REKAM_SPPT = "TGL_REKAM_SPPT";
CONST NIP_PENERIMA_SPPT = "NIP_PENERIMA_SPPT";
CONST TGL_APPROVE_SPPT = "TGL_APPROVE_SPPT";
CONST NIP_APPROVE_SPPT = "NIP_APPROVE_SPPT";
CONST KD_UPT = "KD_UPT";

//TTSPPT12D
CONST TBL_TTSPPT12D = "TTSPPT12D";
CONST KD_BLOK_D = "TTSPPT12D.KD_BLOK";
CONST KD_KELURAHAN_D = "TTSPPT12D.KD_KELURAHAN";
CONST KD_KECAMATAN_D = "TTSPPT12D.KD_KECAMATAN";
CONST KD_DATI2_D = "TTSPPT12D.KD_DATI2";
CONST KD_PROPINSI_D = "TTSPPT12D.KD_PROPINSI";
CONST THN_PAJAK_SPPT_D = "TTSPPT12D.THN_PAJAK_SPPT";
CONST KD_JNS_OP_D = "TTSPPT12D.KD_JNS_OP";
CONST NO_URUT_D = "TTSPPT12D.NO_URUT";
CONST PBB_YG_HARUS_DIBAYAR_SPPT_D = "TTSPPT12D.PBB_YG_HARUS_DIBAYAR_SPPT";
CONST TGL_TERIMA_SPPT_D = "TTSPPT12D.TGL_TERIMA_SPPT";
CONST NM_WP_SPPT_D = "TTSPPT12D.NM_WP_SPPT";

//INPUT POST
CONST NOP = "NOP";
CONST BOOK = "BUKU";

//TTSPPT345
CONST TBL_TTSPPT345 = "TTSPPT345";
CONST THN_PAJAK_SPPT_45 = "THN_PAJAK_SPPT";
CONST KD_JNS_OP_45 = "KD_JNS_OP";
CONST NO_URUT_45 = "NO_URUT";
CONST KD_BLOK_45 = "KD_BLOK";
CONST KD_KELURAHAN_45 = "KD_KELURAHAN";
CONST KD_KECAMATAN_45 = "KD_KECAMATAN";
CONST KD_DATI2_45 = "KD_DATI2";
CONST KD_PROPINSI_45 = "KD_PROPINSI";
CONST NAMA_PENERIMA_SPPT_45 = "NAMA_PENERIMA_SPPT";
CONST NIK_PENERIMA_SPPT_45 = "NIK_PENERIMA_SPPT";
CONST KETERANGAN_45 = "KETERANGAN";
CONST NILAI_PASAR_BUMI_SPPT_45 = "NILAI_PASAR_BUMI_SPPT";
CONST LUAS_BUMI_SPPTBARU_45 = "LUAS_BUMI_SPPTBARU";
CONST LUAS_BNG_SPPTBARU_45 = "LUAS_BNG_SPPTBARU";
CONST TGL_TERIMA_SPPT_45 = "TGL_TERIMA_SPPT";
CONST PBB_YG_HARUS_DIBAYAR_SPPT_45 = "PBB_YG_HARUS_DIBAYAR_SPPT";


//BATAL NOP
CONST TBL_BATALNOP = "BATAL_NOP";

CONST ID_BN = "BATAL_NOP.ID";
CONST NOP_BN = "BATAL_NOP.NOP";
CONST THN_BN = "BATAL_NOP.THN";
CONST ALASAN_BN = "BATAL_NOP.ALASAN";
CONST APPROVED_BN = "BATAL_NOP.APPROVED";
CONST LOGINNAME_BN = "BATAL_NOP.LOGINNAME";
CONST APPROVED_BY_BN = "BATAL_NOP.APPROVED_BY";
CONST UPDATED_DATE_BN = "BATAL_NOP.UPDATED_DATE";
CONST PBB_YG_HARUS_DIBAYAR_SPPT_BN = "BATAL_NOP.PBB_YG_HARUS_DIBAYAR_SPPT";
CONST ALASAN_DETAIL_BN = "BATAL_NOP.ALASAN_DETAIL";

//TBL DS PERUBAHAN OPWP SPPT
CONST TBL_DSPSPPT = "DS_PERUBAHAN_OPWP";

CONST ID_DSP = "DS_PERUBAHAN_OPWP.ID";
CONST NOP_DSP = "DS_PERUBAHAN_OPWP.NOP";
CONST THN_PJK_SPPT_DSP = "DS_PERUBAHAN_OPWP.THN_PAJAK_SPPT";
CONST RT_OP_OLD_DSP = "DS_PERUBAHAN_OPWP.RT_OP_OLD";
CONST RW_OP_OLD_DSP = "DS_PERUBAHAN_OPWP.RW_OP_OLD";
CONST KECAMATAN_OP_NM_OLD_DSP = "DS_PERUBAHAN_OPWP.KECAMATAN_OP_NM_OLD";
CONST KELURAHAN_OP_NM_OLD_DSP = "DS_PERUBAHAN_OPWP.KELURAHAN_OP_NM_OLD";
CONST JALAN_OP_OLD_DSP = "DS_PERUBAHAN_OPWP.JALAN_OP_OLD";
CONST RT_OP_NEW_DSP = "DS_PERUBAHAN_OPWP.RT_OP_NEW";
CONST RW_OP_NEW_DSP = "DS_PERUBAHAN_OPWP.RW_OP_NEW";
CONST KECAMATAN_OP_NM_NEW_DSP = "DS_PERUBAHAN_OPWP.KECAMATAN_OP_NM_NEW";
CONST KELURAHAN_OP_NM_NEW_DSP = "DS_PERUBAHAN_OPWP.KELURAHAN_OP_NM_NEW";
CONST JALAN_OP_NEW_DSP = "DS_PERUBAHAN_OPWP.JALAN_OP_NEW";
CONST RT_WP_OLD_DSP = "DS_PERUBAHAN_OPWP.RT_WP_OLD";
CONST RW_WP_OLD_DSP = "DS_PERUBAHAN_OPWP.RW_WP_OLD";
CONST KECAMATAN_WP_OLD_DSP = "DS_PERUBAHAN_OPWP.KECAMATAN_WP_OLD";
CONST KELURAHAN_WP_NM_OLD_DSP = "DS_PERUBAHAN_OPWP.KELURAHAN_WP_NM_OLD";
CONST JALAN_WP_OLD_DSP = "DS_PERUBAHAN_OPWP.JALAN_WP_OLD";
CONST RT_WP_NEW_DSP = "DS_PERUBAHAN_OPWP.RT_WP_NEW";
CONST RW_WP_NEW_DSP = "DS_PERUBAHAN_OPWP.RW_WP_NEW";
CONST KECAMATAN_WP_NM_NEW_DSP = "DS_PERUBAHAN_OPWP.KECAMATAN_WP_NM_NEW";
CONST KELURAHAN_WP_NM_NEW_DSP = "DS_PERUBAHAN_OPWP.KELURAHAN_WP_NM_NEW";
CONST JALAN_WP_NEW_DSP = "DS_PERUBAHAN_OPWP.JALAN_WP_NEW";
CONST LOGINNAME_DSP = "DS_PERUBAHAN_OPWP.LOGINNAME";
CONST TGL_PERMOHONAN_DSP = "DS_PERUBAHAN_OPWP.TGL_PERMOHONAN";
CONST TGL_APPROVED_DSP = "DS_PERUBAHAN_OPWP.TGL_APPROVED";
CONST APPROVED_BY_DSP = "DS_PERUBAHAN_OPWP.APPROVED_BY";
CONST STATUS_DSP = "DS_PERUBAHAN_OPWP.STATUS";
CONST LUAS_BUMI_OLD_DSP = "DS_PERUBAHAN_OPWP.LUAS_BUMI_OLD";
CONST LUAS_BNG_OLD_DSP = "DS_PERUBAHAN_OPWP.LUAS_BNG_OLD";
CONST LUAS_BUMI_NEW_DSP = "DS_PERUBAHAN_OPWP.LUAS_BUMI_NEW";
CONST LUAS_BNG_NEW_DSP = "DS_PERUBAHAN_OPWP.LUAS_BNG_NEW";
// CONST NOP_DSP = "DS_PERUBAHAN_OPWP.NOP";
CONST THN_PAJAK_SPPT_DSP = "DS_PERUBAHAN_OPWP.THN_PAJAK_SPPT";
CONST GMBRTT12 = "TTSPPT12D.FOTO_PEMBETULAN";

//ehh

// const LOGINNAME = "LOGINNAME";
const PASSWOD = "PASSWOD";
const NAMA = "NAMA";
const EMAIL = "EMAIL";
const NIP = "NIP";
const USER_GROUP = "USER_GROUP";
const KD_KEC = "KD_KEC";
const KD_KEL = "KD_KEL";

const DATA = "data";
const API_URI = "api_uri";
const REQUEST = "request";
const CLIENT = "client";
const MESSAGE = "message";
const SUCCESS = "success";
const CODE = "code";
const METHOD = "method";

const ID_KECPOST = "id_kecamatan";

//HTTP STATUSES
CONST RESP_200 = "OK";
CONST RESP_400 = "Bad request";
CONST RESP_401 = "Unauthorized";
CONST RESP_403 = "Forbidden";
CONST RESP_404 = "Not found";
CONST RESP_405 = "Method not allowed";
CONST RESP_406 = "Not acceptable";
CONST RESP_451 = "Unavailable for legal reasons";
CONST RESP_500 = "Internal server error";
CONST RESP_OK = 200;
CONST RESP_BADREQ = 400;
CONST RESP_UNAUTHORIZED = 401;
CONST RESP_FORBIDDEN = 403;
CONST RESP_NOTFOUND = 404;
CONST RESP_METHODNOTALLOWED = 405;
CONST RESP_NOTACCEPTABLE = 406;
CONST RESP_UNAVAILABLEFORLEGALREASONS = 451;
CONST RESP_INTERNALSERVERERROR = 500;


/* End of file constants.php */
/* Location: ./application/config/constants.php */