<?php

if (! defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class info_rinci_pbb_model extends CI_Model
{
    private $tbl = 'SPPT';

    public function __construct()
    {
        parent::__construct();
    }

    public function getsppt($nopthn)
    {
    	// var_dump($nopthn);die;
		$kd_prop    = substr($nopthn, 0, 2);
        $kd_dati    = substr($nopthn, 2, 2);
        $kd_kec     = substr($nopthn, 4, 3);
        $kd_kel     = substr($nopthn, 7, 3);
        $kd_blok    = substr($nopthn, 10, 3);
        $no_urut    = substr($nopthn, 13, 4);
        $kd_jns_op  = substr($nopthn, 17, 1);
        $thn_pjk    = substr($nopthn, 18, 4);

        $qq = "SELECT S.KD_PROPINSI||'.'||S.KD_DATI2||'-'||S.KD_KECAMATAN||'.'||S.KD_KELURAHAN||'-'||S.KD_BLOK||'.'||S.NO_URUT||'.'||S.KD_JNS_OP AS NOP_LKP, S.THN_PAJAK_SPPT AS TAHUN,S.LUAS_BUMI_SPPT, S.LUAS_BNG_SPPT, 
        CASE WHEN S.LUAS_BUMI_SPPT = 0 THEN 0 ELSE (S.NJOP_BUMI_SPPT/S.LUAS_BUMI_SPPT) END AS NJOP_BUMI_PERM,
        CASE WHEN S.LUAS_BNG_SPPT = 0 THEN 0 ELSE (S.NJOP_BNG_SPPT/S.LUAS_BNG_SPPT) END AS NJOP_BNG_PERM, 
        S.NJOP_BUMI_SPPT, S.NJOP_BNG_SPPT, S.NJOPTKP_SPPT,  S.NJOP_SPPT, 
        S.PBB_YG_HARUS_DIBAYAR_SPPT, S.PBB_TERHUTANG_SPPT, S.FAKTOR_PENGURANG_SPPT,
        S.KD_KLS_BNG, S.KD_KLS_TANAH, '-' as KD_KLS_TANAH_BERSAMA, '-' as KD_KLS_BNG_BERSAMA,
        CASE WHEN S.THN_PAJAK_SPPT < 2024 THEN 100 ELSE 
        (SELECT NILAI_NJKP FROM NJKP WHERE KD_PROPINSI = S.KD_PROPINSI AND KD_DATI2 = S.KD_DATI2 
        AND S.THN_PAJAK_SPPT BETWEEN THN_AWAL AND THN_AKHIR AND S.NJOP_SPPT BETWEEN NJOP_MIN AND NJOP_MAX) END AS NIL_NJKP,
        (SELECT TO_CHAR(NILAI_TARIF, '0.999') FROM TARIF WHERE KD_PROPINSI = S.KD_PROPINSI AND KD_DATI2 = S.KD_DATI2 
        AND S.THN_PAJAK_SPPT BETWEEN THN_AWAL AND THN_AKHIR AND S.NJOP_SPPT BETWEEN NJOP_MIN AND NJOP_MAX) AS NIL_TARIF,
        UPPER(FMT_TGL_TEKS(S.TGL_JATUH_TEMPO_SPPT)) AS TGL_JTTEMPO,
        UPPER(FMT_TGL_TEKS(S.TGL_TERBIT_SPPT)) AS TGL_TERBIT,
        UPPER(FMT_TGL_TEKS(S.TGL_CETAK_SPPT)) AS TGL_CETAK,
        DS.NM_WP, DS.JALAN_WP||' '||DS.BLOK_KAV_NO_WP AS ALAMAT_WP, DS.RT_WP||'/'||DS.RW_WP AS RTRW_WP, DS.KELURAHAN_WP, DS.KOTA_WP,
        DK.JALAN_OP||' '||DK.BLOK_KAV_NO_OP as ALAMAT_OP, DK.RT_OP||'/'||DK.RW_OP AS RTRW_OP, KEC.NM_KECAMATAN, KEL.NM_KELURAHAN,
        NVL(SP.BAYAR_DENDA,0) AS BAYAR_DENDA, NVL(SP.JML_BAYAR,0) AS JML_BAYAR, 
        NVL(SOB.LUAS_BUMI_BEBAN_SPPT,0) AS LUAS_BUMI_BERSAMA, NVL(SOB.LUAS_BNG_BEBAN_SPPT,0) AS LUAS_BNG_BERSAMA, 
        NVL(SOB.NJOP_BUMI_BEBAN_SPPT,0) AS NJOP_BUMI_BERSAMA, NVL(SOB.NJOP_BNG_BEBAN_SPPT,0) AS NJOP_BNG_BERSAMA,
        CASE WHEN (SOB.LUAS_BUMI_BEBAN_SPPT IS NULL OR SOB.LUAS_BUMI_BEBAN_SPPT<= 0) THEN 0 
            ELSE ROUND(SOB.NJOP_BUMI_BEBAN_SPPT/SOB.LUAS_BUMI_BEBAN_SPPT) END AS NJOP_BUMI_BERSAMA_PERM,
        CASE WHEN (SOB.LUAS_BNG_BEBAN_SPPT IS NULL OR SOB.LUAS_BNG_BEBAN_SPPT<= 0) THEN 0 
            ELSE ROUND(SOB.NJOP_BNG_BEBAN_SPPT/SOB.LUAS_BNG_BEBAN_SPPT) END AS NJOP_BNG_BERSAMA_PERM
        FROM SPPT S
        JOIN DAT_OBJEK_PAJAK DK ON S.KD_PROPINSI = DK.KD_PROPINSI AND S.KD_DATI2 = DK.KD_DATI2 
            AND S.KD_KECAMATAN = DK.KD_KECAMATAN AND S.KD_KELURAHAN = DK.KD_KELURAHAN 
            AND S.KD_BLOK = DK.KD_BLOK AND S.NO_URUT = DK.NO_URUT AND S.KD_JNS_OP = DK.KD_JNS_OP
        JOIN DAT_SUBJEK_PAJAK DS ON DS.SUBJEK_PAJAK_ID = DK.SUBJEK_PAJAK_ID
        JOIN REF_KECAMATAN KEC ON KEC.KD_PROPINSI = S.KD_PROPINSI AND KEC.KD_DATI2 = S.KD_DATI2 AND KEC.KD_KECAMATAN = S.KD_KECAMATAN
        JOIN REF_KELURAHAN KEL ON KEL.KD_PROPINSI = S.KD_PROPINSI AND KEL.KD_DATI2 = S.KD_DATI2 
            AND KEL.KD_KECAMATAN = S.KD_KECAMATAN AND KEL.KD_KELURAHAN = S.KD_KELURAHAN
        LEFT JOIN SPPT_OP_BERSAMA SOB ON (S.KD_PROPINSI = SOB.KD_PROPINSI AND S.KD_DATI2=SOB.KD_DATI2 AND S.KD_KECAMATAN=SOB.KD_KECAMATAN 
            AND S.KD_KELURAHAN =SOB.KD_KELURAHAN AND S.KD_BLOK = SOB.KD_BLOK AND S.NO_URUT = SOB.NO_URUT AND S.KD_JNS_OP = SOB.KD_JNS_OP 
            AND S.THN_PAJAK_SPPT = SOB.THN_PAJAK_SPPT)
        LEFT JOIN (SELECT SUM(DENDA_SPPT) AS BAYAR_DENDA, SUM(JML_SPPT_YG_DIBAYAR) AS JML_BAYAR
        		   FROM PEMBAYARAN_SPPT 
        		   WHERE KD_PROPINSI='$kd_prop' AND KD_DATI2='$kd_dati' AND KD_KECAMATAN='$kd_kec' AND KD_KELURAHAN='$kd_kel' 
                   AND KD_BLOK='$kd_blok' AND NO_URUT='$no_urut' AND KD_JNS_OP='$kd_jns_op' AND THN_PAJAK_SPPT='$thn_pjk'
        	) SP ON 1=1
        WHERE S.KD_PROPINSI='$kd_prop' AND S.KD_DATI2='$kd_dati' AND S.KD_KECAMATAN='$kd_kec' AND S.KD_KELURAHAN='$kd_kel' 
        AND S.KD_BLOK='$kd_blok' AND S.NO_URUT='$no_urut' AND S.KD_JNS_OP='$kd_jns_op' AND S.THN_PAJAK_SPPT='$thn_pjk' ";

        $query = $this->db->query($qq);
        if ($query->num_rows()!==0) {
            return $query->row();
        } else {
            return false;
        }
    }

    public function getspptsim($nopthn)
    {
    	// var_dump($nopthn);die;
		$kd_prop    = substr($nopthn, 0, 2);
        $kd_dati    = substr($nopthn, 2, 2);
        $kd_kec     = substr($nopthn, 4, 3);
        $kd_kel     = substr($nopthn, 7, 3);
        $kd_blok    = substr($nopthn, 10, 3);
        $no_urut    = substr($nopthn, 13, 4);
        $kd_jns_op  = substr($nopthn, 17, 1);
        $thn_pjk    = substr($nopthn, 18, 4);

        $qq = "SELECT S.KD_PROPINSI||'.'||S.KD_DATI2||'-'||S.KD_KECAMATAN||'.'||S.KD_KELURAHAN||'-'||S.KD_BLOK||'.'||S.NO_URUT||'.'||S.KD_JNS_OP AS NOP_LKP, S.THN_PAJAK_SPPT AS TAHUN,S.LUAS_BUMI_SPPT, S.LUAS_BNG_SPPT, 
        CASE WHEN S.LUAS_BUMI_SPPT = 0 THEN 0 ELSE (S.NJOP_BUMI_SPPT/S.LUAS_BUMI_SPPT) END AS NJOP_BUMI_PERM,
        CASE WHEN S.LUAS_BNG_SPPT = 0 THEN 0 ELSE (S.NJOP_BNG_SPPT/S.LUAS_BNG_SPPT) END AS NJOP_BNG_PERM, 
        S.NJOP_BUMI_SPPT, S.NJOP_BNG_SPPT, S.NJOPTKP_SPPT,  S.NJOP_SPPT, 
        S.PBB_YG_HARUS_DIBAYAR_SPPT, S.PBB_TERHUTANG_SPPT, S.FAKTOR_PENGURANG_SPPT,
        S.KD_KLS_BNG, S.KD_KLS_TANAH, '-' as KD_KLS_TANAH_BERSAMA, '-' as KD_KLS_BNG_BERSAMA,
        CASE WHEN S.THN_PAJAK_SPPT < 2024 THEN 100 ELSE 
        (SELECT NILAI_NJKP FROM NJKP WHERE KD_PROPINSI = S.KD_PROPINSI AND KD_DATI2 = S.KD_DATI2 
        AND S.THN_PAJAK_SPPT BETWEEN THN_AWAL AND THN_AKHIR AND S.NJOP_SPPT BETWEEN NJOP_MIN AND NJOP_MAX) END AS NIL_NJKP,
        (SELECT TO_CHAR(NILAI_TARIF, '0.999') FROM TARIF WHERE KD_PROPINSI = S.KD_PROPINSI AND KD_DATI2 = S.KD_DATI2 
        AND S.THN_PAJAK_SPPT BETWEEN THN_AWAL AND THN_AKHIR AND S.NJOP_SPPT BETWEEN NJOP_MIN AND NJOP_MAX) AS NIL_TARIF,
        UPPER(FMT_TGL_TEKS(S.TGL_JATUH_TEMPO_SPPT)) AS TGL_JTTEMPO,
        UPPER(FMT_TGL_TEKS(S.TGL_TERBIT_SPPT)) AS TGL_TERBIT,
        UPPER(FMT_TGL_TEKS(S.TGL_CETAK_SPPT)) AS TGL_CETAK,
        DS.NM_WP, DS.JALAN_WP||' '||DS.BLOK_KAV_NO_WP AS ALAMAT_WP, DS.RT_WP||'/'||DS.RW_WP AS RTRW_WP, DS.KELURAHAN_WP, DS.KOTA_WP,
        DK.JALAN_OP||' '||DK.BLOK_KAV_NO_OP as ALAMAT_OP, DK.RT_OP||'/'||DK.RW_OP AS RTRW_OP, KEC.NM_KECAMATAN, KEL.NM_KELURAHAN,
        NVL(SP.BAYAR_DENDA,0) AS BAYAR_DENDA, NVL(SP.JML_BAYAR,0) AS JML_BAYAR, 
        NVL(SOB.LUAS_BUMI_BEBAN_SPPT,0) AS LUAS_BUMI_BERSAMA, NVL(SOB.LUAS_BNG_BEBAN_SPPT,0) AS LUAS_BNG_BERSAMA, 
        NVL(SOB.NJOP_BUMI_BEBAN_SPPT,0) AS NJOP_BUMI_BERSAMA, NVL(SOB.NJOP_BNG_BEBAN_SPPT,0) AS NJOP_BNG_BERSAMA,
        CASE WHEN (SOB.LUAS_BUMI_BEBAN_SPPT IS NULL OR SOB.LUAS_BUMI_BEBAN_SPPT<= 0) THEN 0 
            ELSE ROUND(SOB.NJOP_BUMI_BEBAN_SPPT/SOB.LUAS_BUMI_BEBAN_SPPT) END AS NJOP_BUMI_BERSAMA_PERM,
        CASE WHEN (SOB.LUAS_BNG_BEBAN_SPPT IS NULL OR SOB.LUAS_BNG_BEBAN_SPPT<= 0) THEN 0 
            ELSE ROUND(SOB.NJOP_BNG_BEBAN_SPPT/SOB.LUAS_BNG_BEBAN_SPPT) END AS NJOP_BNG_BERSAMA_PERM
        FROM SPPT_SIMULASI S
        JOIN DAT_OBJEK_PAJAK DK ON S.KD_PROPINSI = DK.KD_PROPINSI AND S.KD_DATI2 = DK.KD_DATI2 
            AND S.KD_KECAMATAN = DK.KD_KECAMATAN AND S.KD_KELURAHAN = DK.KD_KELURAHAN 
            AND S.KD_BLOK = DK.KD_BLOK AND S.NO_URUT = DK.NO_URUT AND S.KD_JNS_OP = DK.KD_JNS_OP
        JOIN DAT_SUBJEK_PAJAK DS ON DS.SUBJEK_PAJAK_ID = DK.SUBJEK_PAJAK_ID
        JOIN REF_KECAMATAN KEC ON KEC.KD_PROPINSI = S.KD_PROPINSI AND KEC.KD_DATI2 = S.KD_DATI2 AND KEC.KD_KECAMATAN = S.KD_KECAMATAN
        JOIN REF_KELURAHAN KEL ON KEL.KD_PROPINSI = S.KD_PROPINSI AND KEL.KD_DATI2 = S.KD_DATI2 
            AND KEL.KD_KECAMATAN = S.KD_KECAMATAN AND KEL.KD_KELURAHAN = S.KD_KELURAHAN
        LEFT JOIN SPPT_OP_BERSAMA SOB ON (S.KD_PROPINSI = SOB.KD_PROPINSI AND S.KD_DATI2=SOB.KD_DATI2 AND S.KD_KECAMATAN=SOB.KD_KECAMATAN 
            AND S.KD_KELURAHAN =SOB.KD_KELURAHAN AND S.KD_BLOK = SOB.KD_BLOK AND S.NO_URUT = SOB.NO_URUT AND S.KD_JNS_OP = SOB.KD_JNS_OP 
            AND S.THN_PAJAK_SPPT = SOB.THN_PAJAK_SPPT)
        LEFT JOIN (SELECT SUM(DENDA_SPPT) AS BAYAR_DENDA, SUM(JML_SPPT_YG_DIBAYAR) AS JML_BAYAR
        		   FROM PEMBAYARAN_SPPT 
        		   WHERE KD_PROPINSI='$kd_prop' AND KD_DATI2='$kd_dati' AND KD_KECAMATAN='$kd_kec' AND KD_KELURAHAN='$kd_kel' 
                   AND KD_BLOK='$kd_blok' AND NO_URUT='$no_urut' AND KD_JNS_OP='$kd_jns_op' AND THN_PAJAK_SPPT='$thn_pjk'
        	) SP ON 1=1
        WHERE S.KD_PROPINSI='$kd_prop' AND S.KD_DATI2='$kd_dati' AND S.KD_KECAMATAN='$kd_kec' AND S.KD_KELURAHAN='$kd_kel' 
        AND S.KD_BLOK='$kd_blok' AND S.NO_URUT='$no_urut' AND S.KD_JNS_OP='$kd_jns_op' AND S.THN_PAJAK_SPPT='$thn_pjk' ";

        $query = $this->db->query($qq);
        if ($query->num_rows()!==0) {
            return $query->row();
        } else {
            return false;
        }
    }

    public function getspptsimtmp($nopthn)
    {
    	// var_dump($nopthn);die;
		$kd_prop    = substr($nopthn, 0, 2);
        $kd_dati    = substr($nopthn, 2, 2);
        $kd_kec     = substr($nopthn, 4, 3);
        $kd_kel     = substr($nopthn, 7, 3);
        $kd_blok    = substr($nopthn, 10, 3);
        $no_urut    = substr($nopthn, 13, 4);
        $kd_jns_op  = substr($nopthn, 17, 1);
        $thn_pjk    = substr($nopthn, 18, 4);

        $qq = "SELECT S.KD_PROPINSI||'.'||S.KD_DATI2||'-'||S.KD_KECAMATAN||'.'||S.KD_KELURAHAN||'-'||S.KD_BLOK||'.'||S.NO_URUT||'.'||S.KD_JNS_OP AS NOP_LKP, S.THN_PAJAK_SPPT AS TAHUN,S.LUAS_BUMI_SPPT, S.LUAS_BNG_SPPT, 
        CASE WHEN S.LUAS_BUMI_SPPT = 0 THEN 0 ELSE (S.NJOP_BUMI_SPPT/S.LUAS_BUMI_SPPT) END AS NJOP_BUMI_PERM,
        CASE WHEN S.LUAS_BNG_SPPT = 0 THEN 0 ELSE (S.NJOP_BNG_SPPT/S.LUAS_BNG_SPPT) END AS NJOP_BNG_PERM, 
        S.NJOP_BUMI_SPPT, S.NJOP_BNG_SPPT, S.NJOPTKP_SPPT,  S.NJOP_SPPT, 
        S.PBB_YG_HARUS_DIBAYAR_SPPT, S.PBB_TERHUTANG_SPPT, S.FAKTOR_PENGURANG_SPPT,
        S.KD_KLS_BNG, S.KD_KLS_TANAH, '-' as KD_KLS_TANAH_BERSAMA, '-' as KD_KLS_BNG_BERSAMA,
        CASE WHEN S.THN_PAJAK_SPPT < 2024 THEN 100 ELSE 
        (SELECT NILAI_NJKP FROM NJKP WHERE KD_PROPINSI = S.KD_PROPINSI AND KD_DATI2 = S.KD_DATI2 
        AND S.THN_PAJAK_SPPT BETWEEN THN_AWAL AND THN_AKHIR AND S.NJOP_SPPT BETWEEN NJOP_MIN AND NJOP_MAX) END AS NIL_NJKP,
        (SELECT TO_CHAR(NILAI_TARIF, '0.999') FROM TARIF WHERE KD_PROPINSI = S.KD_PROPINSI AND KD_DATI2 = S.KD_DATI2 
        AND S.THN_PAJAK_SPPT BETWEEN THN_AWAL AND THN_AKHIR AND S.NJOP_SPPT BETWEEN NJOP_MIN AND NJOP_MAX) AS NIL_TARIF,
        UPPER(FMT_TGL_TEKS(S.TGL_JATUH_TEMPO_SPPT)) AS TGL_JTTEMPO,
        UPPER(FMT_TGL_TEKS(S.TGL_TERBIT_SPPT)) AS TGL_TERBIT,
        UPPER(FMT_TGL_TEKS(S.TGL_CETAK_SPPT)) AS TGL_CETAK,
        DS.NM_WP, DS.JALAN_WP||' '||DS.BLOK_KAV_NO_WP AS ALAMAT_WP, DS.RT_WP||'/'||DS.RW_WP AS RTRW_WP, DS.KELURAHAN_WP, DS.KOTA_WP,
        DK.JALAN_OP||' '||DK.BLOK_KAV_NO_OP as ALAMAT_OP, DK.RT_OP||'/'||DK.RW_OP AS RTRW_OP, KEC.NM_KECAMATAN, KEL.NM_KELURAHAN,
        NVL(SP.BAYAR_DENDA,0) AS BAYAR_DENDA, NVL(SP.JML_BAYAR,0) AS JML_BAYAR, 
        NVL(SOB.LUAS_BUMI_BEBAN_SPPT,0) AS LUAS_BUMI_BERSAMA, NVL(SOB.LUAS_BNG_BEBAN_SPPT,0) AS LUAS_BNG_BERSAMA, 
        NVL(SOB.NJOP_BUMI_BEBAN_SPPT,0) AS NJOP_BUMI_BERSAMA, NVL(SOB.NJOP_BNG_BEBAN_SPPT,0) AS NJOP_BNG_BERSAMA,
        CASE WHEN (SOB.LUAS_BUMI_BEBAN_SPPT IS NULL OR SOB.LUAS_BUMI_BEBAN_SPPT<= 0) THEN 0 
            ELSE ROUND(SOB.NJOP_BUMI_BEBAN_SPPT/SOB.LUAS_BUMI_BEBAN_SPPT) END AS NJOP_BUMI_BERSAMA_PERM,
        CASE WHEN (SOB.LUAS_BNG_BEBAN_SPPT IS NULL OR SOB.LUAS_BNG_BEBAN_SPPT<= 0) THEN 0 
            ELSE ROUND(SOB.NJOP_BNG_BEBAN_SPPT/SOB.LUAS_BNG_BEBAN_SPPT) END AS NJOP_BNG_BERSAMA_PERM
        FROM SPPT_SIMULASI_TMP S
        JOIN DAT_OBJEK_PAJAK DK ON S.KD_PROPINSI = DK.KD_PROPINSI AND S.KD_DATI2 = DK.KD_DATI2 
            AND S.KD_KECAMATAN = DK.KD_KECAMATAN AND S.KD_KELURAHAN = DK.KD_KELURAHAN 
            AND S.KD_BLOK = DK.KD_BLOK AND S.NO_URUT = DK.NO_URUT AND S.KD_JNS_OP = DK.KD_JNS_OP
        JOIN DAT_SUBJEK_PAJAK DS ON DS.SUBJEK_PAJAK_ID = DK.SUBJEK_PAJAK_ID
        JOIN REF_KECAMATAN KEC ON KEC.KD_PROPINSI = S.KD_PROPINSI AND KEC.KD_DATI2 = S.KD_DATI2 AND KEC.KD_KECAMATAN = S.KD_KECAMATAN
        JOIN REF_KELURAHAN KEL ON KEL.KD_PROPINSI = S.KD_PROPINSI AND KEL.KD_DATI2 = S.KD_DATI2 
            AND KEL.KD_KECAMATAN = S.KD_KECAMATAN AND KEL.KD_KELURAHAN = S.KD_KELURAHAN
        LEFT JOIN SPPT_OP_BERSAMA SOB ON (S.KD_PROPINSI = SOB.KD_PROPINSI AND S.KD_DATI2=SOB.KD_DATI2 AND S.KD_KECAMATAN=SOB.KD_KECAMATAN 
            AND S.KD_KELURAHAN =SOB.KD_KELURAHAN AND S.KD_BLOK = SOB.KD_BLOK AND S.NO_URUT = SOB.NO_URUT AND S.KD_JNS_OP = SOB.KD_JNS_OP 
            AND S.THN_PAJAK_SPPT = SOB.THN_PAJAK_SPPT)
        LEFT JOIN (SELECT SUM(DENDA_SPPT) AS BAYAR_DENDA, SUM(JML_SPPT_YG_DIBAYAR) AS JML_BAYAR
        		   FROM PEMBAYARAN_SPPT 
        		   WHERE KD_PROPINSI='$kd_prop' AND KD_DATI2='$kd_dati' AND KD_KECAMATAN='$kd_kec' AND KD_KELURAHAN='$kd_kel' 
                   AND KD_BLOK='$kd_blok' AND NO_URUT='$no_urut' AND KD_JNS_OP='$kd_jns_op' AND THN_PAJAK_SPPT='$thn_pjk'
        	) SP ON 1=1
        WHERE S.KD_PROPINSI='$kd_prop' AND S.KD_DATI2='$kd_dati' AND S.KD_KECAMATAN='$kd_kec' AND S.KD_KELURAHAN='$kd_kel' 
        AND S.KD_BLOK='$kd_blok' AND S.NO_URUT='$no_urut' AND S.KD_JNS_OP='$kd_jns_op' AND S.THN_PAJAK_SPPT='$thn_pjk' ";

        $query = $this->db->query($qq);
        if ($query->num_rows()!==0) {
            return $query->row();
        } else {
            return false;
        }
    }
}