<?php

if (! defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class monitoring_permo_upt_model extends CI_Model {

    public function __construct() {
        parent::__construct();
    }

    function get($param) {

        $sql = "SELECT P.THN_PELAYANAN||P.KD_PROPINSI_PEMOHON||P.KD_DATI2_PEMOHON||P.KD_KECAMATAN_PEMOHON||P.KD_KELURAHAN_PEMOHON
                ||P.KD_BLOK_PEMOHON||P.NO_URUT_PEMOHON||P.KD_JNS_OP_PEMOHON||P.KD_JNS_PELAYANAN AS PO_ID,
                SP.KD_PROPINSI||SP.KD_DATI2||SP.KD_KECAMATAN||SP.KD_KELURAHAN||SP.KD_BLOK||SP.NO_URUT||SP.KD_JNS_OP||TRIM(SP.NIK) AS NOPNIK,
                SP.KD_PROPINSI||'.'||SP.KD_DATI2||'-'||SP.KD_KECAMATAN||'.'||SP.KD_KELURAHAN||'-'||SP.KD_BLOK||'.'||SP.NO_URUT||'.'||SP.KD_JNS_OP AS NOP_LKP,
                SP.KD_PROPINSI||SP.KD_DATI2||SP.KD_KECAMATAN||SP.KD_KELURAHAN||SP.KD_BLOK||SP.NO_URUT||SP.KD_JNS_OP AS NOP,
                SP.NIK AS NIK_REG, SP.NM_WP_SPPT AS NAMA_WP_REG, SP.JLN_WP_SPPT AS ALAMAT_REG, SP.NOHP AS TELP_REG,
                SP.NAMA AS NAMA_REG, SP.EMAIL AS EMAIL_REG,
                P.THN_PELAYANAN||'-'||P.BUNDEL_PELAYANAN||'-'||P.NO_URUT_PELAYANAN as NOPEL,
                P.THN_PELAYANAN, P.BUNDEL_PELAYANAN, P.NO_URUT_PELAYANAN,
                P.NAMA_PEMOHON, P.ALAMAT_PEMOHON, P.KETERANGAN_PST, P.TGL_SURAT_PERMOHONAN, 
                P.THN_PAJAK_PERMOHONAN, P.NO_HP, P.KD_JNS_PELAYANAN, P.NO_SRT_PERMOHONAN,
                L_PERMOHONAN, L_SURAT_KUASA, L_KTP_WP, L_SERTIFIKAT_TANAH, L_SPPT, L_IMB, L_AKTE_JUAL_BELI, L_SK_PENSIUN, 
                L_SPPT_STTS, L_STTS, L_SK_PENGURANGAN, L_SK_KEBERATAN, L_SKKP_PBB, L_SPMKP_PBB, L_LAIN_LAIN, 
                L_PERMOHONAN1, L_SURAT_KUASA1, L_KTP_WP1, L_SERTIFIKAT_TANAH1, L_SPPT1, L_IMB1, L_AKTE_JUAL_BELI1, L_SK_PENSIUN1, 
                L_SPPT_STTS1, L_STTS1, L_SK_PENGURANGAN1, L_SK_KEBERATAN1, L_SKKP_PBB1, L_SPMKP_PBB1, L_LAIN_LAIN1
                FROM PST_PERMOHONAN_TOOL P
                JOIN REG_ESPPT SP ON SP.KD_PROPINSI=P.KD_PROPINSI_PEMOHON AND SP.KD_DATI2=P.KD_DATI2_PEMOHON 
                AND SP.KD_KECAMATAN=P.KD_KECAMATAN_PEMOHON AND P.KD_KELURAHAN_PEMOHON=SP.KD_KELURAHAN AND P.KD_BLOK_PEMOHON=SP.KD_BLOK 
                AND SP.NO_URUT=P.NO_URUT_PEMOHON AND SP.KD_JNS_OP=P.KD_JNS_OP_PEMOHON
                WHERE P.THN_PELAYANAN||P.KD_PROPINSI_PEMOHON||P.KD_DATI2_PEMOHON||P.KD_KECAMATAN_PEMOHON||P.KD_KELURAHAN_PEMOHON
                ||P.KD_BLOK_PEMOHON||P.NO_URUT_PEMOHON||P.KD_JNS_OP_PEMOHON||P.KD_JNS_PELAYANAN = '{$param}' ";
        
        $query = $this->db->query($sql);
        if ($query->num_rows() > 0){
            return $query->row();
        } else { 
            return FALSE;
        }
    }

    function get_by_id($id) {

        $sql = "SELECT P.ID as PPO_ID, P.THN_PELAYANAN||P.KD_PROPINSI_PEMOHON||P.KD_DATI2_PEMOHON||P.KD_KECAMATAN_PEMOHON||P.KD_KELURAHAN_PEMOHON
                ||P.KD_BLOK_PEMOHON||P.NO_URUT_PEMOHON||P.KD_JNS_OP_PEMOHON||P.KD_JNS_PELAYANAN AS PO_ID,
                SP.KD_PROPINSI||SP.KD_DATI2||SP.KD_KECAMATAN||SP.KD_KELURAHAN||SP.KD_BLOK||SP.NO_URUT||SP.KD_JNS_OP||TRIM(SP.NIK) AS NOPNIK,
                SP.KD_PROPINSI||'.'||SP.KD_DATI2||'-'||SP.KD_KECAMATAN||'.'||SP.KD_KELURAHAN||'-'||SP.KD_BLOK||'.'||SP.NO_URUT||'.'||SP.KD_JNS_OP AS NOP_LKP,
                SP.KD_PROPINSI||SP.KD_DATI2||SP.KD_KECAMATAN||SP.KD_KELURAHAN||SP.KD_BLOK||SP.NO_URUT||SP.KD_JNS_OP AS NOP,
                SP.NIK AS NIK_REG, SP.NM_WP_SPPT AS NAMA_WP_REG, SP.JLN_WP_SPPT AS ALAMAT_REG, SP.NOHP AS TELP_REG,
                SP.NAMA AS NAMA_REG, SP.EMAIL AS EMAIL_REG,
                P.THN_PELAYANAN||'-'||P.BUNDEL_PELAYANAN||'-'||P.NO_URUT_PELAYANAN as NOPEL,
                P.THN_PELAYANAN, P.BUNDEL_PELAYANAN, P.NO_URUT_PELAYANAN,
                P.NAMA_PEMOHON, P.ALAMAT_PEMOHON, P.KETERANGAN_PST, P.TGL_SURAT_PERMOHONAN, 
                P.THN_PAJAK_PERMOHONAN, P.NO_HP, P.KD_JNS_PELAYANAN, P.NO_SRT_PERMOHONAN,
                L_PERMOHONAN, L_SURAT_KUASA, L_KTP_WP, L_SERTIFIKAT_TANAH, L_SPPT, L_IMB, L_AKTE_JUAL_BELI, L_SK_PENSIUN, 
                L_SPPT_STTS, L_STTS, L_SK_PENGURANGAN, L_SK_KEBERATAN, L_SKKP_PBB, L_SPMKP_PBB, L_LAIN_LAIN, 
                L_PERMOHONAN1, L_SURAT_KUASA1, L_KTP_WP1, L_SERTIFIKAT_TANAH1, L_SPPT1, L_IMB1, L_AKTE_JUAL_BELI1, L_SK_PENSIUN1, 
                L_SPPT_STTS1, L_STTS1, L_SK_PENGURANGAN1, L_SK_KEBERATAN1, L_SKKP_PBB1, L_SPMKP_PBB1, L_LAIN_LAIN1
                FROM PST_PERMOHONAN_TOOL P
                JOIN REG_ESPPT SP ON SP.KD_PROPINSI=P.KD_PROPINSI_PEMOHON AND SP.KD_DATI2=P.KD_DATI2_PEMOHON 
                AND SP.KD_KECAMATAN=P.KD_KECAMATAN_PEMOHON AND P.KD_KELURAHAN_PEMOHON=SP.KD_KELURAHAN AND P.KD_BLOK_PEMOHON=SP.KD_BLOK 
                AND SP.NO_URUT=P.NO_URUT_PEMOHON AND SP.KD_JNS_OP=P.KD_JNS_OP_PEMOHON
                WHERE P.ID = '{$id}' ";
        
        $query = $this->db->query($sql);
        if ($query->num_rows() > 0){
            return $query->row();
        } else { 
            return FALSE;
        }
    }

    function get_jns_ply() {
        $in_array = "('02','03')";
        $qq = "SELECT * FROM REF_JNS_PELAYANAN WHERE KD_JNS_PELAYANAN IN {$in_array} ";        
        return $this->db->query($qq)->result();
    }
    
}

/* End of file _model.php */
